### ISSUE TITLE
Figure out swerve

### ISSUE THREAD

**Issue by grappell** [team5419/Request-TARS#1]
# How?
- Probably using CTRE swerve
    - This would require pheonix 6
- Port of our current swerve
- Steal more of the Citrus's code (very appealing)

**Comment by cyndiac** [comment]
API documentation: https://api.ctr-electronics.com/phoenix6/release/java/com/ctre/phoenix6/mechanisms/swerve/package-summary.html

**Comment by grappell** [comment]
Added general code in commit 8de0da7 pulling from [here](https://github.com/team5419/CTRE-Default-Swerve)

**Comment by grappell** [comment]
Finished in the CTRE Swerve branch
